# Generated by Django 5.2.8 on 2025-11-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Розничная цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='storage.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
