# Generated by Django 5.2.8 on 2025-11-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_updated_at'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='product.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='supply.supply', verbose_name='Поставщик')),
            ],
        ),
    ]
